config/routes.rb
Rails.application.routes.draw do
  resources :games do
    resources :guesses, only: :create
  end

  root 'hangman#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :guesses, dependent: :destroy

  validates :word, presence: true,
                   length: { maximum: 20 },
                   format: { with: /\A[a-zA-Z]+\z/ }
  validates :lives, numericality: { only_integer: true,
                                    less_than_or_equal_to: 10,
                                    greater_than: 0 }

  def guesses_list
    guesses.map(&:letter)
  end

  def remaining_lives
    lives - guesses.length + correct_guesses.length
  end

  def game_over?
    game_won? || game_lost?
  end

  def game_lost?
    remaining_lives.zero?
  end

  def game_won?
    all_letters_guessed?
  end

  def letter_in_word?(letter)
    word.downcase.include? letter
  end

  private

  def correct_guesses
    word.downcase.split('').uniq & guesses_list
  end

  def all_letters_guessed?
    (word.downcase.chars - correct_guesses).empty?
  end
end

app/models/guess.rb
class Guess < ApplicationRecord
  belongs_to :game

  validates :letter, presence: true,
                     uniqueness: { scope: :game_id },
                     length: { maximum: 1 },
                     format: { with: /[a-zA-Z]/, message: "must be a letter" }

  before_validation :downcase_guess, on: :create

  private

  def downcase_guess
    begin
      letter.downcase!
    rescue; end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
require_relative '../services/random_word_generator'

class GamesController < ApplicationController
  before_action :set_game, only: %i[show edit update destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show; end

  # GET /games/new
  def new
    @game = Game.new
  end

  # POST /games
  # POST /games.json
  def create
    if params[:game]
      @game = Game.new(new_game_params)
    else
      @game = Game.new word: ::RandomWordGenerator.generate_word
    end

    respond_to do |format|
      if @game.save
        flash[:success] = 'Game was successfully created.'
        format.html { redirect_to @game }
        format.json { render :show, status: :created, location: @game }
      else
        @errors = @game.errors.full_messages
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    respond_to do |format|
      if @game.destroy
        flash[:success] = 'Game was successfully destroyed.'
        format.html { redirect_to games_url }
        format.json { head :no_content }
      else
        flash[:danger] = 'Game was not destroyed.'
        format.html { redirect_to games_url }
        format.json { head :no_content, @game.errors }
      end
    end
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def new_game_params
    params.require(:game).permit(:word, :lives)
  end
end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController
  def create
    respond_to do |format|
      @game = Game.find(params[:game_id])
      @guess = @game.guesses.create(guess_params)
      @game.reload
      if @guess.valid?
        if @game.letter_in_word?(@guess.letter)
          flash[:success] = 'Correct guess'
        else
          flash[:danger] = 'Incorrect guess'
        end
        format.html { redirect_to @game }
        format.json { render :show, status: :created, location: @game }
      else
        @errors = @guess.errors.full_messages
        format.html { render 'games/show' }
        format.json { render json: @guess.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def guess_params
    params.require(:guess).permit(:letter)
  end
end

app/controllers/hangman_controller.rb
class HangmanController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
  def masked_word(game)
    ''.tap do |revealed_letters|
      game.word.split('').each do |letter|
        if game.guesses_list.include? letter.downcase
          revealed_letters << letter
        else
          revealed_letters << '-'
        end
      end
    end
  end
end

app/helpers/guesses_helper.rb
module GuessesHelper
end

app/helpers/hangman_helper.rb
module HangmanHelper
end

app/views/games/_errors.html.erb
<% if errors %>
  <% if errors.any? %>
    <div id="error_explanation">
      <%= pluralize(errors.count, "error") %> prohibited this game from being saved

      <ul>
      <% errors.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/games/_game_over.html.erb
<% if game.game_won? %>
  <div class="alert alert-success">You won!</div>
<% elsif game.game_lost? %>
  <div class="alert alert-danger">
    Game lost! The word was <strong><mark><%= game.word %></mark></strong>
  </div>
<% end %>

app/views/games/index.html.erb
<div class="row">
  <div class="col-md-2">
    <%= link_to 'Create a custom game', new_game_path, class: 'btn btn-default btn-sm' %>
  </div>

  <div class="col-md-2">
    <%= form_with(model: Game, local: true) do |form| %>
      <div class="actions">
        <%= form.submit 'Create game with a random word', class: 'btn btn-default btn-sm' %>
      </div>
    <% end %>
  </div >
</div>

<h1>Games</h1>
<br>

<table class="table">
  <thead>
    <tr>
      <th>Word</th>
      <th>Guesses</th>
      <th>Lives</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= masked_word(game) %></td>
        <td><%= game.guesses_list.join(' ') %></td>
        <td><%= game.remaining_lives %></td>
        <td><%= link_to 'Show', game, class: 'btn btn-default btn-xs'%></td>
        <td><%= link_to 'Destroy', game, class: 'btn btn-warning btn-xs', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'errors', errors: @errors %>

<%= form_with(model: @game, local: true) do |form| %>

  <div class="field form-group">
    <%= form.label :word, class: 'control-label' %>
    <%= form.text_field :word, id: :game_word, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :lives, class: 'control-label' %>
    <%= form.number_field :lives, id: :game_lives, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-default btn-block btn-sm' %>
  </div>
<% end %>

<%= link_to 'Back', games_path, class: 'btn btn-default btn-sm back-btn' %>

app/views/games/show.html.erb
<%= render 'games/game_over', game: @game %>
<%= render 'games/errors', errors: @errors %>

<p>
  <strong>Word:</strong>
  <%= masked_word(@game) %>
</p>

<p>
  <strong>Guesses:</strong>
  <%= @game.guesses_list.join(' ') %>
</p>

<p>
  <strong>Lives:</strong>
  <%= @game.remaining_lives %>
</p>


<% unless @game.game_over? %>
  <%= form_with(model: [ @game, @game.guesses.build ], local: true, html: {class: 'form-inline'}) do |form| %>

      <%= form.label "Guess a letter", class: 'control-label' %>
      <div class="field form-group">
        <%= form.text_field :letter, id: :game_word, class: 'form-control' %>
      </div>

      <div class="actions form-group">
        <%= form.submit 'Submit', class: 'btn btn-default btn-sm'%>
      </div>
  <% end %>
<% end %>

<%= link_to 'Back', games_path, class: 'btn btn-default btn-sm' %>

app/views/hangman/index.html.erb
<h1>Let's play HANGMAN!</h1>

<%= link_to 'Go to games', games_path, class: 'btn btn-default btn-sm' %>

app/views/hangman/show.html.erb
<h1>Let's play HANGMAN!</h1>

<%= link_to 'Go to games', games_path, class: 'btn btn-default btn-sm' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsHangman</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Hangman</a>
        </div>
      </div>
    </nav>

    <div id="main-container" class="container">
      <div class="row">
          <% flash.each do |name, msg| -%>
            <%= content_tag :div, msg.html_safe, class: "alert alert-#{name}" %>
          <% end -%>
          <%= yield %>
      </div>
    </div>
  </body>
</html>